version: '3.8'

services:
  db:
    image: postgres:16
    container_name: tutor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tutor_db
      POSTGRES_USER: tutor_user
      POSTGRES_PASSWORD: tutor_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # Puedes agregar otros servicios aquí, por ejemplo:
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ...
  # app:
  #   build: ./app
  #   ...

volumes:
  postgres_data:
